services:
  blog_server:
    container_name: blog_server
    build:
      context: ../../
      dockerfile: ./docker/server/prod.dockerfile
    ports:
      - 8000:80
    env_file:
      - ../../.env.prod
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      blog_postgress:
        condition: service_healthy
    volumes:
      - ../../:/app
      - /home/harsh/manhattan_data/ssl_cert:/ssl_cert
    restart: unless-stopped

  blog_postgress:
    image: postgres
    container_name: blog_postgress
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dhKJHdhsjh376HFjksdh38
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
