basePath: /
definitions:
  health.HelloResponse:
    properties:
      data:
        type: integer
      msg:
        type: string
    type: object
  homepage.ArticlesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/homepage.Blog'
        type: array
      msg:
        type: string
    type: object
  homepage.Blog:
    properties:
      author_name:
        type: string
      author_profile_url:
        type: string
      blog_created_at:
        type: string
      blog_id:
        type: integer
      blog_thumbnail_url:
        type: string
      category:
        items:
          type: string
        type: array
      description:
        type: string
      read_time:
        type: integer
      title:
        type: string
    type: object
  homepage.FeaturedResponse:
    properties:
      data:
        $ref: '#/definitions/homepage.Blog'
      msg:
        type: string
    type: object
  types.ErrResponse:
    properties:
      err:
        type: string
      msg:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: github.com/tetrex
  description: This is a backend api server
  license:
    name: MIT License
  title: server api
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: returns server time
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HelloResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get Health check status
      tags:
      - Health
  /home/articles:
    get:
      consumes:
      - application/json
      description: returns array of articles
      parameters:
      - description: int valid
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - description: int valid
        in: query
        maximum: 100
        minimum: 0
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/homepage.ArticlesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get homepage articles
      tags:
      - Homepage
  /home/featured:
    get:
      consumes:
      - application/json
      description: returns featured article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/homepage.FeaturedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrResponse'
      summary: Get featured article
      tags:
      - Homepage
swagger: "2.0"
